### ISSUE TITLE
Image.setPixel(Color4 c, int x, int y) is not implemented for PixelFormat.RGBA_FLOAT

### ISSUE THREAD

**Issue by minexew** [gecko0307/dlib#107]
:(

**Comment by gecko0307** [comment]
The problem is, `Color4` is not directly compatible with floating-point images. It is used to convert `Color4f` to integer pixel format (8 or 16 bit), but not vise-versa. It is actually just a vector of ushorts without bit depth information. We could assume that it stores 8-bit color, but isn't assigning such low precision data to HDR image somewhat pointless?

**Comment by minexew** [comment]
Oh, right, I completely missed the subtle difference between Color4 and Color4f. I agree that assigning 8-bit values makes no sense in this case.
The reason why I brought up `setPixel` in the first place is that `opIndexAssign` depends on it. So, with `setPixel` not supporting float, there seems to be no public API to set pixels in a float image.

**Comment by gecko0307** [comment]
You mean `opIndexAssign` in `Image`? Float image exists separately from it, in `dlib.image.hdri`. It is an independent implementation of `SuperImage`.

**Comment by minexew** [comment]
Ooooooooh, that clears things up.
