### ISSUE TITLE
Event loop crashes under Windows

### ISSUE THREAD

**Issue by gecko0307** [gecko0307/dlib#115]
Or am I doing something wrong? Here is the code:

```d
void main()
{
    Socket s = MmapPool.instance.make!Socket(AddressFamily.inet, SocketType.stream, ProtocolType.ip);
    char[] ip = cast(char[])"127.0.0.1";
    ushort port = 8192;
    InternetAddress adr = MmapPool.instance.make!InternetAddress(ip, port);
    s.bind(adr);
    s.listen(5);
    ConnectionWatcher io = MmapPool.instance.make!ConnectionWatcher(s);
    io.setProtocol!EchoProtocol;
    Loop loop = MmapPool.instance.make!Loop();
    loop.start(io);
    loop.run();
}
```

```
core.exception.RangeError@dlib\async\loop.d(229): Range violation
----------------
0x0047B1F8 in _d_arraybounds
0x00402780 in void dlib.async.loop.Loop.start(dlib.async.watcher.ConnectionWatcher) at C:\Users\DNS-PC\Documents\tim\projects\dlib-testbed\dlib\async\loop.d(229)
0x0047B0C2 in _Dmain at C:\Users\DNS-PC\Documents\tim\projects\dlib-testbed\main.d(54)
0x0048C56F in D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv
0x0048C533 in void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll()
0x0048C434 in _d_run_main
0x0047B0E4 in main at C:\Users\DNS-PC\Documents\tim\projects\dlib-testbed\dlib\async\loop.d(7)
0x004C9125 in mainCRTStartup
0x76D3919F in BaseThreadInitThunk
0x77DCAD1F in RtlInitializeExceptionChain
0x77DCACEA in RtlInitializeExceptionChain
```

My guess is this is somehow related to `MmapPool`, which doesn't correctly allocate `connections` array in `Loop` constructor.

**Comment by belka-ew** [comment]
`Loop` is an abstract class and isn't implemented currently for Windows. I wonder why the compiler doesn't complain. Normally you would use getDefaultLoop() but it will return `null` for Windows. Windows uses completely different asynchronous model (IOCP), that requires another socket implementation and some work on the event loop. I'm currently working on it and in a week or two it should be ready (see my last message on gitter).
As far as I know there are no D native IOCP implementations. All D event loops use Unix-compatible but old and not very performant event loop models. So maybe there will be the first one :)

btw a question:
There are "Completion ports" on Windows. They allow to do read/write operations asynchronously. But they belong neither to filesystem nor to network, because they can be used with normal files and with the sockets aswell. Any idea where to put them? Maybe something like "io" package or one of the existing ones?

**Comment by gecko0307** [comment]
Ah, I see. I'm very new to asynchronous programming, so apologies.
I think completion ports can live in the same async package.

**Comment by belka-ew** [comment]
Just to define the problem more precisely:
Event loops depend on the event model supported the operating system. It means the operating system should notify you if there are new connections or some data to read or write. And there differend kinds of such event models.

`poll` and `select` are two old ones, supported everywhere (Linux, Windows, BSD, Max), but not very performent.
Therefore every system has its own event model that can scale in modern servers.

- `epoll` - supported only on Linux. Is implemented but a bit broken because of my Windows related changes.
- `kqueue` - BSD and OSX (althrough Marc Lehmann says, it is awfully broken on Mac, but if I understand correctly he means only "extended" features like signals). I didn't want to implement Kqueue originally but a few days ago I installed FreeBSD and it is almost working now (in my dlib fork) :)
- `IOCP` - Windows only. Is implemented now (in my dlib fork).

`select`, `poll`, `epoll` and `kqueue` are similar. They aren't really asynchronous, but non-blocking. You can think of a single-core CPU that can't run the tasks asynchronously but only one task per time, but it can schedule the tasks, so you have a feeling it is running asynchronously.

Windows IOCP is truly asynchronous. It requires a bit different way of thinking and has different problems. Therefore many event loops have problems with IOCP if they was desigend for BSD sockets. Btw I've found one D-implemention of IOCP, so we won't be the first, but it will be the first GC-free  implementation ;)

**Comment by belka-ew** [comment]
Were you able to test it if it works now? For Windows you would need something like:
```d
import dlib.async;
import dlib.network.socket;

class EchoProtocol : TransmissionControlProtocol
{
    private DuplexTransport transport;

    void received(ubyte[] data)
    {
        transport.write(data);
    }

    void connected(DuplexTransport transport)
    {
        this.transport = transport;
    }

    void disconnected()
    {
    }
}

void main()
{
    auto sock = new OverlappedStreamSocket(AddressFamily.INET);
    auto address = new InternetAddress("127.0.0.1", cast(ushort) 8192);

    sock.bind(address);
    sock.listen(5);
    auto io = new ConnectionWatcher(sock);
    io.setProtocol!EchoProtocol;
    defaultLoop.start(io);
    defaultLoop.run();

    sock.shutdown();
}
```
I finish with the event loop for now. I will add features in the future, as far as I need more.
Now I've started to work on a crypto package and will be able to make the first pull request in the next days with the first algorithm (DES is almost ready)

**Comment by belka-ew** [comment]
forgotten: `disconnected` accepts now a SocketExcepton as argument, which is set if an error occures.
so the signature is
`disconnected(SocketException exception = null)`

should fix it in the docs.

**Comment by gecko0307** [comment]
Now it works indeed. But I've encountered another problem. I've tried to implement a simple "Hello, World" HTTP server, but for some reason, it freezes at `received`:
```d
class EchoProtocol: TransmissionControlProtocol
{
    private DuplexTransport transport;
    
    string responce = 
  "HTTP/1.1 200 OK\r\nContent-Type: text/html; charset=UTF-8\r\n<html><body>Hello, world!</body></html>\r\n";

    void received(ubyte[] data)
    {
        writeln(cast(char[])data);
        transport.write(cast(ubyte[])responce);
    }

    void connected(DuplexTransport transport)
    {
        this.transport = transport;
    }

    void disconnected(SocketException exception = null)
    {
    }
}
```

**Comment by gecko0307** [comment]
Oh, never mind, I forgot Content-Length in responce :)

**Comment by belka-ew** [comment]
It shouldn't crash anyway. I will check if I can reproduce it. Nice to have someone to work with: poblems can be found faster :) Thanks
