### ISSUE TITLE
Add access to file-mode-bits

### ISSUE THREAD

**Issue by gizmomogwai** [gecko0307/dlib#132]
I wanted to try to write a ls-like dlang program with the help of dlib and its nice fs-abstraction (perhaps in the long run comparable to https://the.exa.website/)
Unfortunately the mode-flags are not part of the api.
Is it possible to add this in a generic way? I do not even know how this maps to windows.

**Comment by gecko0307** [comment]
In dlib.filesystem files are accessed as streams (`InputStream`, `OutputStream`, `IOStream`), so access modes are abstractized with corresponding interface methods (`openForInput`, `openForOutput`, `openForIO`). But, actually, access modes can be implemented with a simple final method in `FileSystem` interface. It can look like this:

```d
final auto openFile(uint accessFlags, uint creationFlags = create)(string filename)
{
    static if ((read & write) & accessFlags)
        return openForIO(filename, creationFlags);
    else static if (write & accessFlags)
        return openForOutput(filename, creationFlags);
    else static if (read & accessFlags)
        return openForInput(filename);
    else
        static assert(0);
}
```

I can add it if you wish. The only limitation is that its behaviour will be static, based on template parameters - otherwise every implementation of `FileSystem` will be required to provide their own `openFile`, which is also possible, but less convenient.

**Comment by gizmomogwai** [comment]
At the moment I am only interested in the modes, without even opening the file.
Like the information ls is showing: e.g.

    -rw-r--r--  1 user_nama  staff  41 Mar 15  2015 .bashrc

If a file in theory would be writeable, readable by me or others. I understand that this is a questions that always raises "problems" in fs-abstractions, as the models for potential candidates of filesystems are vastly different, e.g. local filesystem, zip-filesystem, amazon cloud store, smb, nfs, ...

**Comment by gecko0307** [comment]
In principle, this kind of information could be obtained via `FileStat` from `FileSystem.stat()`.
