### ISSUE TITLE
Publishing DDoc documentation

### ISSUE THREAD

**Issue by minexew** [gecko0307/dlib#23]
`dub --build=docs` generates DDoc documentation.
Most modules are not documented right now, but for those few that are it would be nice to be able to publish the documentation online. Can we do this with just github? Just pushing these to the repo will display them as HTML source code.

**Comment by gecko0307** [comment]
I've made a simple workaround: a script that generates HTML from wiki pages. See it in gendoc folder.

**Comment by belka-ew** [comment]
Hey,

I also was asked to publish the documentation for the event loop, because some people (and I can understand it) don't like to search through the source code.

I wanted before to create a subdomain on my site for it but since it is now in dlib, I thought maybe we could create a webpage for dlib and dlib related projects.

I could register some domain (e.g. .org, .com, .info or something else). My intention is to write a web framework and web server. And @gecko0307 can put some infos about dmech and game development in D. And API-documentation for everything from ddoc of cause.

- We can get just a ready CMS. Then we have administration tools for quick publishing and editing
- or use dlib itself and put everything online using the event loop. For the beginning it would be just html pages with some styles. It would be then "self-hosted", but a bit ugly for the first time (maybe for a long time, because it is a lot of work to write a server and a kind of CMS), because a nice design and publishing tools would be missing. But it would be enough for people to find quickly a documentation. I have a server, so running the D-code isn't a problem.

**Comment by gecko0307** [comment]
Now it's possible to generate deploy-ready documentation (even with index and search): `dub --build=ddox`. It is hosted [here](https://gecko0307.github.io/dlib/docs).
